# Generated by Django 5.1.4 on 2024-12-17 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robots", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="robot",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="robot",
            name="model",
            field=models.CharField(
                max_length=2,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Модель должна быть двух-символьной последовательностью из букв или цифр.",
                        regex="^[A-Za-z0-9]{2}$",
                    ),
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.MaxLengthValidator(2),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="robot",
            name="serial",
            field=models.CharField(
                max_length=5,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Serial должен быть в формате 'model-version', где 'model' это 2 буквы или цифры, а 'version' это 1 или 2 цифры.",
                        regex="^[A-Za-z0-9]{2}-[A-Za-z0-9]{1,2}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="robot",
            name="version",
            field=models.CharField(
                max_length=2,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Версия должна быть одно/двух-символьной последовательностью из букв или цифр.",
                        regex="^[A-Za-z0-9]{1,2}$",
                    ),
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.MaxLengthValidator(2),
                ],
            ),
        ),
    ]
